[package]
name = "aws-smithy-inlineable"
version = "0.0.0-smithy-rs-head"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Zelda Hessler <zhessler@amazon.com>"]
description = """
The modules of this crate are intended to be inlined directly into smithy clients as needed. The dependencies here
are to allow this crate to be compilable and testable in isolation, no client code actually takes these dependencies.
"""
edition = "2021"
license = "Apache-2.0"
publish = false
repository = "https://github.com/awslabs/smithy-rs"

[dependencies]
aws-smithy-client = { path = "../aws-smithy-client" }
aws-smithy-http = { path = "../aws-smithy-http" }
aws-smithy-types = { path = "../aws-smithy-types" }
http = "0.2.8"
tower-service = "0.3.2"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
