[workspace]

members = [
    "smithy-http",
    "smithy-client",
    "smithy-eventstream",
    "smithy-http-tower",
    "smithy-json",
    "smithy-query",
    "smithy-types",
    "smithy-xml",
    "inlineable"
]
