[workspace]

members = [
    "inlineable",
    "aws-smithy-async",
    "aws-smithy-checksums",
    "aws-smithy-client",
    "aws-smithy-eventstream",
    "aws-smithy-http",
    "aws-smithy-http-auth",
    "aws-smithy-http-server",
    "aws-smithy-http-server-python",
    "aws-smithy-http-tower",
    "aws-smithy-interceptor",
    "aws-smithy-json",
    "aws-smithy-orchestrator",
    "aws-smithy-protocol-test",
    "aws-smithy-query",
    "aws-smithy-token-bucket",
    "aws-smithy-types",
    "aws-smithy-types-convert",
    "aws-smithy-xml",
]
