[workspace]

members = [
    "inlineable",
    "smithy-async",
    "smithy-client",
    "smithy-eventstream",
    "smithy-http",
    "smithy-http-tower",
    "smithy-json",
    "smithy-protocol-test",
    "smithy-query",
    "smithy-types",
    "smithy-xml"
]
