# This Cargo.toml is unused in generated code. It exists solely to enable these tests to compile in-situ
[package]
name = "s3-tests"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-s3 = { path = "../../build/aws-sdk/s3" }
http = "0.2.3"
bytes = "1"
