# This Cargo.toml is unused in generated code. It exists solely to enable these tests to compile in-situ
[package]
name = "s3-tests"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-s3 = { path = "../../build/aws-sdk/sdk/s3" }
aws-smithy-client = { path = "../../build/aws-sdk/sdk/aws-smithy-client", features = ["test-util"] }
aws-smithy-http = { path = "../../build/aws-sdk/sdk/aws-smithy-http" }
aws-smithy-async = { path = "../../build/aws-sdk/sdk/aws-smithy-async" }
tracing-subscriber = "0.2.18"

[dev-dependencies]
aws-http = { path = "../../build/aws-sdk/sdk/aws-http"}
aws-hyper = { path = "../../build/aws-sdk/sdk/aws-hyper"}
bytes = "1"
http = "0.2.3"
serde_json = "1"
tokio  = { version = "1", features = ["full"]}
