[package]
name = "aws-smithy-http-server"
version = "0.1.0"
authors = ["Matteo Bigoi <matbigoi@amazon.com>", "David Pérez <davidpz@amazon.com>"]
edition = "2018"
description = """
Server traits and utilities used by the code generator.
"""

[dependencies]
aws-smithy-http = { path = "../aws-smithy-http" }
bytes = "1.1"
http = "0.2"

[dev-dependencies]
pretty_assertions = "1"
