# This Cargo.toml is unused in generated code. It exists solely to enable these tests to compile in-situ
[package]
name = "iam-tests"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-iam = { path = "../../build/aws-sdk/iam" }
aws-endpoint = { path = "../../build/aws-sdk/aws-endpoint" }
smithy-client = { path = "../../build/aws-sdk/smithy-client", features = ["test-util"] }
smithy-http = { path = "../../build/aws-sdk/smithy-http" }
tracing-subscriber = "0.2.18"

[dev-dependencies]
tokio  = { version = "1", features = ["full"]}
http = "0.2.3"
bytes = "1"
aws-hyper = { path = "../../build/aws-sdk/aws-hyper"}
aws-http = { path = "../../build/aws-sdk/aws-http"}
