allowed_external_types = [
    "aws_smithy_types::config_bag::Storable",
    "aws_smithy_types::config_bag::StoreReplace",
    "aws_smithy_types::config_bag::Storer",

    # TODO(https://github.com/awslabs/smithy-rs/issues/1193): Switch to AsyncIterator once standardized
    "futures_core::stream::Stream",

    # TODO(https://github.com/awslabs/smithy-rs/issues/1193): Don't expose `SendError`
    "tokio::sync::mpsc::error::SendError",
]
