# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"

[[aws-sdk-rust]]
message = "_Internal:_ Update sync script to run gradle clean. This fixes an issue where codegen was not triggered when only properties changed."
author = "rcoh"
meta = { "breaking" = false, "tada" = false, "bug" = true }
references = ["smithy-rs#1100"]
