# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false, "target" = "client | server | all"}
# author = "rcoh"

[[smithy-rs]]
message = "The `Debug` implementation for `PropertyBag` now prints a list of the types it contains. This significantly improves debuggability."
author = "rcoh"
references = ["smithy-rs#2612"]
meta = { "breaking" = false, "tada" = false, "bug" = false }

[[smithy-rs]]
message = """
- rust runtime
  - Implements serde support to `Number`, `Blob`, `Document`, `DateTime`

- Core codegen code
  - Add sensitive warning
  - Add `serde` attributes
  - Import `serde` crate to enable `serde(skip)` on some namespaces
  - Add `serde` crate behind unstable feature gate on `Cargo.toml`

- Client codegen code
  - add `serde` as dependency behind feature gate
  - add `serde` support to uknown variant types
"""
author = "thomas-k-cameron"
references = ["smithy-rs#2615"]
meta = { "breaking" = false, "tada" = false, "bug" = false }

[[aws-sdk-rust]]
message = """
- rust runtime
  - Implements serde support to `Number`, `Blob`, `Document`, `DateTime`

- Core codegen code
  - Add sensitive warning
  - Add `serde` attributes
  - Import `serde` crate to enable `serde(skip)` on some namespaces
  - Add `serde` crate behind unstable feature gate on `Cargo.toml`

- Client codegen code
  - add `serde` as dependency behind feature gate
  - add `serde` support to uknown variant types
"""
author = "thomas-k-cameron"
references = ["smithy-rs#2615"]

[[smithy-rs]]
message = "Implement `Ord` and `PartialOrd` for `DateTime`."
author = "henriiik"
references = ["smithy-rs#2653"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
