# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false, "target" = "client | server | all"}
# author = "rcoh"

[[aws-sdk-rust]]
message = "Add support for v1 `http_body::Body` to `aws_smithy_types::byte_stream::bytestream_util::PathBody`."
references = ["smithy-rs#1925", "smithy-rs#3673"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "Velfi"

[[smithy-rs]]
message = "Add support for v1 `http_body::Body` to `aws_smithy_types::byte_stream::bytestream_util::PathBody`."
references = ["smithy-rs#1925", "smithy-rs#3673"]
meta = { "breaking" = false, "tada" = false, "bug" = false, "target" = "all"}
author = "Velfi"

[[smithy-rs]]
message = "Enable aws-smithy-runtime to compile in rustc 1.72.1"
references = ["smithy-rs#3675"]
meta = { "breaking" = false, "tada" = false, "bug" = true, "target" = "client" }
author = "dastrom"

[[aws-sdk-rust]]
message = "Fix S3 ListParts API paginator infinite loop."
references = ["aws-sdk-rust#1143"]
meta = { "breaking" = false, "tada" = false, "bug" = true }
author = "landonxjames"

[[smithy-rs]]
message = "Fix S3 ListParts API paginator infinite loop."
references = ["aws-sdk-rust#1143"]
meta = { "breaking" = false, "tada" = false, "bug" = true, "target" = "client"}
author = "landonxjames"
