# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false, "target" = "client | server | all"}
# author = "rcoh"
[[smithy-rs]]
message = """
Fix `name` and `absolute` methods on `OperationExtension`.

The older, [now removed](https://github.com/awslabs/smithy-rs/pull/2161), service builder would insert `OperationExtension` into the `http::Response` containing the [absolute shape ID](https://smithy.io/2.0/spec/model.html#grammar-token-smithy-AbsoluteRootShapeId) with the `#` symbol replaced with a `.`. When [reintroduced](https://github.com/awslabs/smithy-rs/pull/2157) into the new service builder machinery the behavior was changed - we now do _not_ perform the replace. This change fixes the documentation and `name`/`abosolute` methods of the `OperationExtension` API to match this new behavior.

In the old service builder, `OperationExtension` was initialized, by the framework, and then used as follows:

```rust
let ext = OperationExtension::new("com.amazonaws.CompleteSnapshot");

// This is expected
let name = ext.name(); // "CompleteSnapshot"
let namespace = ext.namespace(); // = "com.amazonaws";
```

On reintroduction, `OperationExtension` was iniialized, by the `Plugin`, and then used as follows:

```rust
let ext = OperationExtension::new("com.amazonaws#CompleteSnapshot");

// This is the bug
let name = ext.name(); // "amazonaws#CompleteSnapshot"
let namespace = ext.namespace(); // = "com";
```

The intended behavior is now restored:

```rust
let ext = OperationExtension::new("com.amazonaws#CompleteSnapshot");

// This is expected
let name = ext.name(); // "CompleteSnapshot"
let namespace = ext.namespace(); // = "com.amazonaws";
```

The rationale behind this change is that the previous design was tailored towards a specific internal use case and shouldn't be enforced on all customers.
"""
references = ["smithy-rs#2276"]
meta = { "breaking" = true, "tada" = false, "bug" = true, "target" = "server"}
author = "hlbarber"
