# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"

[[smithy-rs]]
message = "Fix link to Developer Guide in crate's README.md"
references = ["smithy-rs#1262"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "liubin"

[[aws-sdk-rust]]
message = "Fix link to Developer Guide in crate's README.md"
references = ["smithy-rs#1262"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "liubin"

[[smithy-rs]]
message = "Update all runtime crates to [edition 2021](https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html)"
references = ["aws-sdk-rust#490"]
meta = { "breaking" = true, "tada" = false, "bug" = false }
author = "Velfi"

[[aws-sdk-rust]]
message = "Update all SDK and runtime crates to [edition 2021](https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html)"
references = ["aws-sdk-rust#490"]
meta = { "breaking" = true, "tada" = false, "bug" = false }
author = "Velfi"
