# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"

[[aws-sdk-rust]]
message = """
The `meta`, `environment`, and `dns` Cargo feature flags were removed from `aws-config`.
The code behind the `dns` flag is now enabled when `rt-tokio` is enabled. The code behind
the `meta` and `environment` flags is always enabled now.
"""
references = ["smithy-rs#961"]
meta = { "breaking" = true, "tada" = false, "bug" = false }
author = "jdisanti"

[[aws-sdk-rust]]
message = "Debug implementation of Credentials will print `expiry` in a human readable way"
meta = { "breaking" = false, "tada" = false, "bug" = false }
references = ["smithy-rs#973"]
author = "rcoh"
