# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"

[[aws-sdk-rust]]
message = """
The `meta`, `environment`, and `dns` Cargo feature flags were removed from `aws-config`.
The code behind the `dns` flag is now enabled when `rt-tokio` is enabled. The code behind
the `meta` and `environment` flags is always enabled now.
"""
references = ["smithy-rs#961"]
meta = { "breaking" = true, "tada" = false, "bug" = false }
author = "jdisanti"

[[aws-sdk-rust]]
message = "Debug implementation of Credentials will print `expiry` in a human readable way."
meta = { "breaking" = false, "tada" = false, "bug" = false }
references = ["smithy-rs#973"]
author = "rcoh"

[[aws-sdk-rust]]
message = "Add Route53 customization to trim `/hostedzone/` prefix prior to serialization. This fixes a bug where round-tripping a hosted zone id resulted in an error."
meta = { "breaking" = false, "tada" = false, "bug" = true }
references = ["smithy-rs#999", "smithy-rs#143", "aws-sdk-rust#344" ]
author = "rcoh"

[[aws-sdk-rust]]
message = "Fix bug where ECS credential provider could not perform retries."
meta = { "breaking" = false, "tada" = false, "bug" = true }
references = ["smithy-rs#998", "aws-sdk-rust#359"]
author = "rcoh"

[[aws-sdk-rust]]
message = "`aws_http::AwsErrorRetryPolicy` was moved to `aws_http::retry::AwsErrorRetryPolicy`."
meta = { "breaking" = true, "tada" = false, "bug" = false }
references = ["smithy-rs#1003"]
author = "rcoh"

[[smithy-rs]]
message = "The signature of `aws_smithy_protocol_test::validate_headers` was made more flexible but may require adjusting invocations slightly."
meta = { "breaking" = true, "tada" = false, "bug" = false }
references = ["smithy-rs#1003"]
author = "rcoh"

[[aws-sdk-rust]]
message = "Add recursion detection middleware to the default stack"
meta = { "breaking" = false, "tada" = false, "bug" = false }
references = ["smithy-rs#1003"]
author = "rcoh"

[[aws-sdk-rust]]
message = "aws_types::Config is now `Clone`"
meta = { "breaking" = false, "tada" = false, "bug" = false }
references = ["smithy-rs#1002", "aws-sdk-rust#352"]
author = "rcoh"

[[smithy-rs]]
message = "Add support for paginators! Paginated APIs now include `.paginate()` and (when supported) `.paginate().items()` to enable paginating responses automatically. The paginator API should be considered in preview and is subject to change pending customer feedback."
meta = { "breaking" = false, "tada" = true, "bug" = false }
references = ["aws-sdk-rust#47", "smithy-rs#1006"]
author = "rcoh"

[[aws-sdk-rust]]
message = "Add support for paginators! Paginated APIs now include `.paginate()` and (when supported) `.paginate().items()` to enable paginating responses automatically. The paginator API should be considered in preview and is subject to change pending customer feedback."
meta = { "breaking" = false, "tada" = true, "bug" = false }
references = ["aws-sdk-rust#47", "smithy-rs#1006"]
author = "rcoh"
