# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false, "target" = "client | server | all"}
# author = "rcoh"

[[aws-sdk-rust]]
message = "EKS Pod Identity is now supported as part of the default ECS credential provider."
references = ["smithy-rs#3416"]
meta = { "breaking" = false, "bug" = false, "tada" = true }
author = "jackkleeman"

[[smithy-rs]]
message = "Added aws-smithy-wasm crate to enable SDK use in WASI compliant environments"
references = ["smithy-rs#2087", "smithy-rs#2520", "smithy-rs#3409", "aws-sdk-rust#59"]
meta = { "breaking" = false, "tada" = true, "bug" = false }
authors = ["landonxjames", "eduardomourar"]

[[smithy-rs]]
message = "Added aws-smithy-wasm crate to enable SDK use in WASI compliant environments"
references = ["smithy-rs#2087", "smithy-rs#2520", "smithy-rs#3409"]
meta = { "breaking" = false, "tada" = true, "bug" = false, "target" = "client"}
authors = ["landonxjames", "eduardomourar"]

[[smithy-rs]]
message = "[`SdkBody`](https://docs.rs/aws-smithy-types/latest/aws_smithy_types/body/struct.SdkBody.html) now implements the 1.0 version of the `http_body::Body` trait."
references = ["smithy-rs#3365", "aws-sdk-rust#1046"]
meta = { "breaking" = false, "tada" = true, "bug" = false, "target" = "all" }
authors = ["cayman-amzn", "rcoh"]

[[aws-sdk-rust]]
message = "Add support for Lambda's `InvokeWithResponseStreaming` and Bedrock Agent Runtime's `InvokeAgent` operations."
references = ["aws-sdk-rust#1075", "aws-sdk-rust#1080", "smithy-rs#3451"]
meta = { "breaking" = false, "bug" = false, "tada" = true }
author = "jdisanti"

[[aws-sdk-rust]]
message = "Added support for SSO bearer token authentication. The aws-sdk-codecatalyst crate can now send requests without erroring."
references = ["aws-sdk-rust#703", "smithy-rs#3453"]
meta = { "breaking" = false, "bug" = false, "tada" = true }
author = "jdisanti"
