# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false, "sdk" = "client | server | all"}
# author = "rcoh"

[[smithy-rs]]
message = "Rename EventStreamInput to EventStreamSender"
references = ["smithy-rs#1157"]
meta = { "breaking" = true, "tada" = false, "bug" = false, "sdk" = "all" }
author = "82marbag"

[[aws-sdk-rust]]
message = "Rename EventStreamInput to EventStreamSender"
references = ["smithy-rs#1157"]
meta = { "breaking" = true, "tada" = false, "bug" = false, "sdk" = "client" }
author = "82marbag"

[[aws-sdk-rust]]
message = "Generate event stream specific error types"
references = ["smithy-rs#1157"]
meta = { "breaking" = true, "tada" = false, "bug" = false, "sdk" = "client" }
author = "82marbag"

[[aws-sdk-rust]]
message = "EventStreamSender and Receiver use event stream specific error types"
references = ["smithy-rs#1157"]
meta = { "breaking" = true, "tada" = false, "bug" = false, "sdk" = "client" }
author = "82marbag"

[[smithy-rs]]
message = "Generate event stream specific error types"
references = ["smithy-rs#1157"]
meta = { "breaking" = true, "tada" = false, "bug" = false, "sdk" = "all" }
author = "82marbag"

[[smithy-rs]]
message = "EventStreamSender and Receiver use event stream specific error types"
references = ["smithy-rs#1157"]
meta = { "breaking" = true, "tada" = false, "bug" = false, "sdk" = "all" }
author = "82marbag"
