# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false, "target" = "client | server | all"}
# author = "rcoh"

[[smithy-rs]]
message = "Retry additional classes of H2 errors (H2 GoAway & H2 ResetStream)"
references = ["aws-sdk-rust#738", "aws-sdk-rust#858"]
meta = { "breaking" = false, "tada" = false, "bug" = false, "target" = "client" }
author = "rcoh"

[[aws-sdk-rust]]
message = "Retry additional classes of H2 errors (H2 GoAway & H2 ResetStream)"
references = ["aws-sdk-rust#738", "aws-sdk-rust#858"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "rcoh"
