# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"

[[aws-sdk-rust]]
message = "Include non-service-specific examples in the root Cargo workspace so that they can build"
references = ["smithy-rs#957"]
meta = { "breaking" = false, "tada" = false, "bug" = true }
author = "jdisanti"

[[smithy-rs]]
message = "Include non-service-specific examples in the generated root Cargo workspace"
references = ["smithy-rs#957"]
meta = { "breaking" = false, "tada" = false, "bug" = true }
author = "jdisanti"

[[smithy-rs]]
message = "Make `aws-smithy-client` a required dependency in generated services."
references = ["smithy-rs#979"]
meta = { "breaking" = false, "tada" = false, "bug" = true }
author = "rcoh"

[[aws-sdk-rust]]
message = "Make `aws-smithy-client` a required dependency in generated services."
references = ["smithy-rs#979"]
meta = { "breaking" = false, "tada" = false, "bug" = true }
author = "rcoh"
