# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false, "target" = "client | server | all"}
# author = "rcoh"

[[aws-sdk-rust]]
message = "Add support for `[sso-session]` in AWS config file for AWS Identity Center SSO credentials."
references = ["aws-sdk-rust#703", "smithy-rs#3379"]
meta = { "breaking" = false, "tada" = true, "bug" = false }
author = "jdisanti"
