# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false, "target" = "client | server | all"}
# author = "rcoh"

[[smithy-rs]]
message = "The MSRV has been increase to 1.74.1"
references = ["smithy-rs#3410"]
meta = { "bug" = false, "breaking" = false, tada = false, target = "all" }
author = "rcoh"

[[aws-sdk-rust]]
message = "The MSRV has been increase to 1.74.1"
references = ["smithy-rs#3410"]
meta = { "bug" = false, "breaking" = false, tada = false }
author = "rcoh"
