# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"

[[aws-sdk-rust]]
message = "The docs for fluent builders now have easy links to their corresponding Input, Output, and Error structs"
references = ["aws-sdk-rust#348"]
meta = { "breaking" = false, "tada" = true, "bug" = false }
author = "Velfi"

[[aws-sdk-rust]]
message = "Fix typos for X-Ray trace ID environment variable in aws_http::recursion_detection"
references = ["smithy-rs#1050"]
meta = { "breaking" = false, "tada" = false, "bug" = true }
author = "nmoutschen"
