# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"

[[aws-sdk-rust]]
message = """
Add support for aws-chunked content encoding. Only single-chunk encoding is supported. Multiple chunks and
chunk signing are not supported at this time.
"""
references = ["smithy-rs#1263"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "Velfi"

[[aws-sdk-rust]]
message = "Re-export aws_types::SdkConfig in aws_config"
references = ["smithy-rs#1457"]
meta = { "breaking" = false, "tada" = true, "bug" = false }
author = "calavera"

[[aws-sdk-rust]]
message = "aws-smithy-client: Support using rustls with either native roots or webpki-roots"
meta = { "breaking" = false, "tada" = true, "bug" = false }
author = "joshtriplett"

[[aws-sdk-rust]]
message = "aws-smithy-client: Upgrade hyper-rustls to 0.23.0"
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "joshtriplett"
