# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false, "target" = "client | server | all"}
# author = "rcoh"

[[smithy-rs]]
message = "Support `stringArray` type in endpoints params"
references = ["smithy-rs#3742"]
meta = { "breaking" = false, "tada" = false, "bug" = false, "target" = "client" }
author = "landonxjames"

[[aws-sdk-rust]]
message = "Fix bug where stalled stream protection would panic with an underflow if the first event was logged too soon."
references = ["smithy-rs#3744"]
meta = { "breaking" = false, "tada" = false, "bug" = true }
author = "Velfi"

[[smithy-rs]]
message = "Fix bug where stalled stream protection would panic with an underflow if the first event was logged too soon."
references = ["smithy-rs#3744"]
meta = { "breaking" = false, "tada" = false, "bug" = true, "target" = "client" }
author = "Velfi"

[[smithy-rs]]
message = """
`FromParts<Protocol>::Rejection` must implement `std::fmt::Display`.

An operation handler can accept user-defined data types as long as they implement
[FromParts<Protocol>](https://docs.rs/aws-smithy-http-server/latest/aws_smithy_http_server/request/trait.FromParts.html).
The trait has an associated type [`Rejection`](https://docs.rs/aws-smithy-http-server/latest/aws_smithy_http_server/request/trait.FromParts.html#associatedtype.Rejection).
Whatever data type is set for `Rejection` must now implement (at least) [`std::fmt::Display`](https://doc.rust-lang.org/std/fmt/trait.Display.html).
Additionally, it is recommended to implement [`std::error::Error`](https://doc.rust-lang.org/std/error/trait.Error.html) for that type.

This requirement is necessary to help us write error log entries when the parameter that the operation handler expects fails to be
constructed from the request parts.
"""
references = ["smithy-rs#3746"]
meta = { "breaking" = true, "tada" = false, "bug" = false, "target" = "server" }
author = "drganjoo"
