# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
[[aws-sdk-rust]]
message = '''
If you directly depend on AWS or Smithy runtime crates _(e.g., AWS crates not named `aws-config` or prefixed with `aws-sdk-`)_,
the formerly default features from those crates must now be explicitly set in your `Cargo.toml`.


**Upgrade guide**

| before                          | after |
|---------------------------------|-------|
| `aws-sigv4 = "VERSION"`         | `aws-sigv4 = { version = "VERSION", features = ["sign-http"] }` |
| `aws-smithy-async = "VERSION"`  | `aws-smithy-async = { version = "VERSION", features = ["rt-tokio"] }` |
| `aws-smithy-client = "VERSION"` | `aws-smithy-client = { version = "VERSION", features = ["client-hyper", "rustls", "rt-tokio"] }` |
| `aws-smithy-http = "VERSION"`   | `aws-smithy-http = { version = "VERSION", features = ["bytestream-util"] }` |
'''
references = ["smithy-rs#930"]
meta = { "breaking" = true, "tada" = false, "bug" = false }
author = "zhessler"

[[smithy-rs]]
message = '''
Runtime crates no longer have default features. You must now specify the features that you want when you add a dependency to your `Cargo.toml`.

**Upgrade guide**

| before | after |
|--------|-------|
| `aws-sigv4 = "VERSION"`         | `aws-sigv4 = { version = "VERSION", features = ["sign-http"] }` |
| `aws-smithy-async = "VERSION"`  | `aws-smithy-async = { version = "VERSION", features = ["rt-tokio"] }` |
| `aws-smithy-client = "VERSION"` | `aws-smithy-client = { version = "VERSION", features = ["client-hyper", "rustls", "rt-tokio"] }` |
| `aws-smithy-http = "VERSION"`   | `aws-smithy-http = { version = "VERSION", features = ["bytestream-util"] }` |
'''
references = ["smithy-rs#930"]
meta = { "breaking" = true, "tada" = false, "bug" = false }
author = "zhessler"

[[aws-sdk-rust]]
message = "Use provided `sleep_impl` for retries instead of using Tokio directly."
references = ["smithy-rs#923"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "rcoh"

[[smithy-rs]]
message = "Use provided `sleep_impl` for retries instead of using Tokio directly."
references = ["smithy-rs#923"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "rcoh"

[[aws-sdk-rust]]
message = "Fix typos in module documentation for generated crates"
references = ["smithy-rs#920"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "rcoh"

[[smithy-rs]]
message = "Fix typos in module documentation for generated crates"
references = ["smithy-rs#920"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "rcoh"

[[smithy-rs]]
message = "Avoid serializing repetitive `xmlns` attributes in generated XML serializers."
references = ["aws-sdk-rust#301", "smithy-rs#892"]
meta = { "breaking" = false, "tada" = false, "bug" = true }
author = "rcoh"

[[aws-sdk-rust]]
message = "Avoid serializing repetitive `xmlns` attributes when serializing XML. This reduces the length of serialized requests and should improve compatibility with localstack."
references = ["aws-sdk-rust#301", "smithy-rs#892"]
meta = { "breaking" = false, "tada" = false, "bug" = true }
author = "rcoh"

[[smithy-rs]]
message = "Add changelog automation to sdk-lints"
references = ["smithy-rs#922", "smithy-rs#914"]
meta = { "breaking" = false, "tada" = true, "bug" = false }
author = "rcoh"
