[package]
name = "aws-smithy-wasm"
version = "0.1.0"
authors = [
  "AWS Rust SDK Team <aws-sdk-rust@amazon.com>",
  "Eduardo Rodrigues <16357187+eduardomourar@users.noreply.github.com>",
]
description = "Smithy WebAssembly configuration for smithy-rs."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[target.'cfg(all(target_family = "wasm", target_os = "wasi"))'.dependencies]
# [dependencies]
aws-smithy-runtime-api = { path = "../aws-smithy-runtime-api", features = ["http-1x"]}
aws-smithy-http = { path = "../aws-smithy-http" }
aws-smithy-types = { path = "../aws-smithy-types" }
bytes = "1"
http = "1.0.0"
tower = "0.4.13"
tracing = "0.1.40"
wasi = "0.12.0+wasi-0.2.0"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
