[package]
name = "aws-smithy-retries"
version = "0.0.0-smithy-rs-head"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Zelda Hessler <zhessler@amazon.com>"]
description = """
Smithy code related to retry handling and token bucket. This code defines when and how failed requests should be retried.
It also defines the behavior used to limit the rate that requests are sent."
"""
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.25", features = ["sync"] }
aws-smithy-types = { path = "../aws-smithy-types" }
http = "0.2.8"
http-body = "0.4.5"
