# This Cargo.toml is unused in generated code. It exists solely to enable these tests to compile in-situ
[package]
name = "dynamo-tests"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-auth = { path = "../../build/aws-sdk/aws-auth" }
aws-http = { path = "../../build/aws-sdk/aws-http" }
aws-hyper = { path = "../../build/aws-sdk/aws-hyper" }
aws-types = { path = "../../build/aws-sdk/aws-types" }
aws-sdk-dynamodb = { path = "../../build/aws-sdk/dynamodb" }
bytes = "1"
criterion = { version = "0.3.4" }
http = "0.2.4"
serde_json = "1"
smithy-client = { path = "../../build/aws-sdk/smithy-client", features = ["test-util"] }
smithy-http = { path = "../../build/aws-sdk/smithy-http" }
smithy-types = { path = "../../build/aws-sdk/smithy-types" }
tokio = { version = "1", features = ["full", "test-util"]}
tracing-subscriber = "0.2.16"

[[bench]]
name = "deserialization_bench"
harness = false

[[bench]]
name = "serialization_bench"
harness = false
