[package]
name = "sdk-lints"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
cargo_toml = "0.10.1"
clap = { version = "3.1.7", features = ["derive"]}
toml = "0.5.8"
serde = { version = "1", features = ["derive"]}
lazy_static = "1.4.0"
