[package]
name = "sdk-lints"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
anyhow = "1"
cargo_toml = "0.10.1"
serde = { version = "1", features = ["derive"]}
