# These are the allowed external types in the `aws-sdk-*` generated crates, checked by CI.
allowed_external_types = [
    "aws_credential_types::*",
    "aws_http::*",
    "aws_runtime::*",
    "aws_smithy_async::*",
    "aws_smithy_http::*",
    "aws_smithy_runtime::*",
    "aws_smithy_runtime_api::*",
    "aws_smithy_types::*",
    "aws_types::*",

    "http::header::map::HeaderMap",
    "http::header::value::HeaderValue",
    "http::request::Request",
    "http::error::Error",
    "http::uri::Uri",
    "http::method::Method",

    # TODO(https://github.com/awslabs/smithy-rs/issues/1193): Once tooling permits it, only allow the following types in the `event-stream` feature
    "aws_smithy_eventstream::*",
]
