[crates]
aws-config = ["1.0.0"]
aws-endpoint = ["0.60.0"]
aws-http = ["0.60.0"]
aws-hyper = ["0.60.0"]
aws-runtime = ["1.0.0"]
aws-runtime-api = ["1.0.0"]
aws-sig-auth = ["0.60.0"]
aws-sigv4 = ["1.0.0"]
aws-smithy-async = ["1.0.1"] # Oh no, aws-smithy-async already has 1.0.1 published!
aws-smithy-checksums = ["0.60.0"]
aws-smithy-client = ["0.60.0"]
aws-smithy-eventstream = ["0.60.0"]
aws-smithy-http = ["0.60.0"]
aws-smithy-http-auth = ["0.60.0"]
aws-smithy-http-server = ["0.60.0"]
aws-smithy-http-server-python = ["0.60.0"]
aws-smithy-http-server-typescript = ["0.60.0"]
aws-smithy-http-tower = ["0.60.0"]
aws-smithy-json = ["0.60.0"]
aws-smithy-protocol-test = ["0.60.0"]
aws-smithy-query = ["0.60.0"]
aws-smithy-runtime = ["1.0.0"]
aws-smithy-runtime-api = ["1.0.0"]
aws-smithy-types = ["1.0.0"]
aws-smithy-types-convert = ["0.60.0"]
aws-smithy-xml = ["0.60.0"]
aws-types = ["1.0.0"]
