[package]
name = "config-code-examples"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>", "Doug Schwartz <dougsch@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { path = "../../build/aws-sdk/aws-config" }
aws-sdk-config = { package = "aws-sdk-config", path = "../../build/aws-sdk/config" }
tokio = { version = "1", features = ["full"] }
actix-rt = "*"
structopt = { version = "0.3", default-features = false }
tracing-subscriber = "0.2.18"
