[package]
name = "smithy-rs-sync"
version = "0.1.0"
edition = "2021"
description = "A CLI tool to replay commits from smithy-rs, generate code, and commit that code to aws-rust-sdk"
authors = ["Zelda Hessler <zhessler@amazon.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Having this here prevents this tool from being included in a higher-level workspace
[workspace]

[profile.release]
# prefer fast compile time over runtime performance
opt-level = 0

[dependencies]
anyhow = "1"
clap = { version = "3.1.7", features = ["derive"] }
git2 = "0.13"
gitignore = "1"
smithy-rs-tool-common = { version = "0.1", path = "../smithy-rs-tool-common" }

[dev-dependencies]
pretty_assertions = "1"
tempdir = "0.3"
