[package]
name = "smithy-rs-sync"
version = "0.1.0"
edition = "2018"
description = "A CLI tool to replay commits from smithy-rs, generate code, and commit that code to aws-rust-sdk"
authors = ["Zelda Hessler <zhessler@amazon.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Having this here prevents this tool from being included in a higher-level workspace
[workspace]

[dependencies]
anyhow = "1"
git2 = "0.13"
gitignore = "1"
structopt = { version = "0.3", default-features = false }

[dev-dependencies]
pretty_assertions = "1"
tempdir = "0.3"
