[package]
name = "inlineable"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"
description = """
The modules of this crate are intended to be inlined directly into the SDK as needed.
"""

[dependencies]
"serde" = { version ="1", features = ["derive"] }
"serde_json" = "1"
"http" = "0.2.1"
"smithy-types" = { version = "0.0.1", path = "../smithy-types" }

[dev-dependencies]
proptest = "0.10.1"
