[package]
name = "aws-smithy-runtime"
version = "0.0.0-smithy-rs-head"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Zelda Hessler <zhessler@amazon.com>"]
description = "The new smithy runtime crate"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
http-auth = ["aws-smithy-runtime-api/http-auth"]
test-util = ["dep:aws-smithy-protocol-test"]

[dependencies]
aws-smithy-async = { path = "../aws-smithy-async" }
aws-smithy-client = { path = "../aws-smithy-client" }
aws-smithy-http = { path = "../aws-smithy-http" }
aws-smithy-protocol-test = { path = "../aws-smithy-protocol-test", optional = true }
aws-smithy-runtime-api = { path = "../aws-smithy-runtime-api" }
aws-smithy-types = { path = "../aws-smithy-types" }
bytes = "1"
http = "0.2.8"
http-body = "0.4.5"
pin-project-lite = "0.2.7"
pin-utils = "0.1.0"
tokio = { version = "1.25", features = [] }
tracing = "0.1"

[dev-dependencies]
aws-smithy-async = { path = "../aws-smithy-async", features = ["rt-tokio"] }
tokio = { version = "1.25", features = ["macros", "rt", "test-util"] }

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
