[package]
name = "canary-runner"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
description = "Tool used to run the canary tests in CI"
edition = "2021"
license = "Apache-2.0"
publish = false

[workspace]

[dependencies]
anyhow = "1"
async-trait = "0.1.56"
aws-config = "0.46"
aws-sdk-cloudwatch = "0.16"
aws-sdk-lambda = "0.16"
aws-sdk-s3 = "0.16"
base64 = "0.13"
clap = { version = "~3.1.18", features = ["derive"] }
lazy_static = "1"
octorust = "0.1.37"
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smithy-rs-tool-common = { version = "0.1", path = "../../smithy-rs-tool-common", features = ["async-shell"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
