[package]
name = "smithy-eventstream"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "John DiSanti <jdisanti@amazon.com>"]
edition = "2018"

[dependencies]
bytes = "1"
crc32fast = "1"
smithy-types = { path = "../smithy-types" }
