# Without this configuration, the workspace will be read from `rust-runtime`, causing the build to fail.
[workspace]
members = [
    "pokemon-service",
    "pokemon-service-sdk",
    "pokemon-service-client"
]
