[package]
name = "smithy-http"
version = "0.0.1"
authors = ["rcoh@amazon.com"]
edition = "2018"

[dependencies]
smithy-types = { path = "../smithy-types" }

[dev-dependencies]
proptest = "0.10.1"
base64 = "0.13.0"