# This Cargo.toml is unused in generated code. It exists solely to enable these tests to compile in-situ
[package]
name = "qldb-tests"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>", "Shing Lyu <shinglyu@amazon.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-http = { path = "../../build/aws-sdk/aws-http" }
aws-hyper = { path = "../../build/aws-sdk/aws-hyper" }
aws-sdk-qldbsession = { path = "../../build/aws-sdk/qldbsession" }
aws-smithy-client = { path = "../../build/aws-sdk/aws-smithy-client", features = ["test-util"] }
aws-smithy-http = { path = "../../build/aws-sdk/aws-smithy-http" }
aws-smithy-types = { path = "../../build/aws-sdk/aws-smithy-types" }
http = "0.2.3"
tokio = { version = "1", features = ["full"]}
tracing-subscriber = "0.2.16"
