blank_issues_enabled: true
contact_links:
- name: Report a security vulnerability
  url: https://github.com/awslabs/smithy-rs/security/policy
  about: Please review our security policy for more details
