[package]
name = "dynamo-helloworld"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynamodb = { version = "0.0.1", path = "../../build/aws-sdk/dynamodb" }
aws-auth = { path = "../../build/aws-sdk/aws-auth" }
aws-types = { path = "../../build/aws-sdk/aws-types" }
tokio = { version = "1", features = ["full"] }
smithy-http = { path = "../../build/aws-sdk/smithy-http" }
http = "0.2.3"
env_logger = "0.8.2"
