[package]
name = "aws-smithy-observability-otel"
version = "0.1.0"
authors = [
  "AWS Rust SDK Team <aws-sdk-rust@amazon.com>",
]
description = "Smithy OpenTelemetry observability implementation."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[dependencies]
aws-smithy-observability = { path = "../aws-smithy-observability" }
opentelemetry = {version = "0.26.0", features = ["metrics"]}
# The below dependencies are transitive, but must be pinned until we can generate a new lockfile
# lockfile generation currently blocked by aws-lc-sys build issue
value-bag = "1.10.0"
async-global-executor = "2.4.1"
async-task = "=4.7.1"

# This crate cannot beused on powerpc
[target.'cfg(not(target_arch = "powerpc"))'.dependencies]
opentelemetry_sdk = {version = "0.26.0", features = ["metrics", "testing"]}

[dev-dependencies]
tokio = { version = "1.23.1" }

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
