[package]
name = "aws-smithy-observability-otel"
version = "0.1.0"
authors = [
  "AWS Rust SDK Team <aws-sdk-rust@amazon.com>",
]
description = "Smithy OpenTelemetry observability implementation."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[dependencies]
aws-smithy-observability = { path = "../aws-smithy-observability" }
opentelemetry = {version = "0.26.0", features = ["metrics"]}
opentelemetry_sdk = {version = "0.26.0", features = ["metrics", "testing"]}

[dev-dependencies]
tokio = { version = "1.23.1" }

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
