# This Cargo.toml is unused in generated code. It exists solely to enable these tests to compile in-situ
[package]
name = "glacier-tests"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-glacier = { path = "../../build/aws-sdk/sdk/glacier" }
aws-smithy-client = { path = "../../build/aws-sdk/sdk/aws-smithy-client", features = ["test-util"] }
aws-smithy-protocol-test = { path = "../../build/aws-sdk/sdk/aws-smithy-protocol-test"}
tracing-subscriber = "0.2.18"

[dev-dependencies]
tokio  = { version = "1", features = ["full"]}
http = "0.2.3"
bytes = "1"
aws-hyper = { path = "../../build/aws-sdk/sdk/aws-hyper"}
aws-http = { path = "../../build/aws-sdk/sdk/aws-http"}
