#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

[package]
name = "stub"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "*"
aws-credential-types = { version = "*", features = ["hardcoded-credentials"] }
aws-sdk-sts = "*"
aws-smithy-client = { version = "*", features = ["rustls"] }
exitcode = "1"
hyper-rustls = { version = "0.24", features = ["rustls-native-certs", "http2"] }
rustls = "0.21"
rustls-native-certs = "0.6"
rustls-pemfile = "1"
tokio = { version = "1", features = ["full"] }
x509-parser = "0.15"
