[package]
name = "telephone-game"
version = "0.1.0"
authors = ["Zelda Hessler <zhessler@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { path = "../../build/aws-sdk/aws-config" }
aws-sdk-polly = { package = "aws-sdk-polly", path = "../../build/aws-sdk/polly" }
aws-sdk-s3 = { package = "aws-sdk-s3", path = "../../build/aws-sdk/s3" }
aws-sdk-transcribe = { package = "aws-sdk-transcribe", path = "../../build/aws-sdk/transcribe" }
anyhow = "1.0.44"
clap = "3.0.0-beta.4"
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.14"
rodio = "0.14.0"
serde_json = "1.0.68"
tempdir = "0.3.7"
tokio = { version = "1", features = ["full"] }
