# Note: this workspace exists solely for the convenience of running tests. These packages will all eventually
# end up in the final SDK workspace.
[workspace]
members = [
    "applicationautoscaling",
    "autoscaling",
    "autoscalingplans",
    "batch",
    "cloudformation",
    "cloudwatch",
    "cloudwatchlogs",
    "cognitoidentity",
    "cognitoidentityprovider",
    "cognitosync",
    "config",
    "dynamo-add-item",
    "dynamo-create-table",
    "dynamo-delete-item",
    "dynamo-delete-table",
    "dynamo-helloworld",
    "dynamo-list-items",
    "dynamo-list-tables",
    "dynamo-movies",
    "ebs",
    "ec2",
    "ecr",
    "ecs",
    "eks",
    "iam",
    "kinesis",
    "kms",
    "lambda",
    "medialive",
    "mediapackage",
    "polly",
    "qldb",
    "rds",
    "rdsdata",
    "route53",
    "s3",
    "sagemaker",
    "secretsmanager",
    "ses",
    "snowball",
    "sns",
    "sqs",
    "ssm",
    "sts"
]

[profile.dev]
split-debuginfo = "unpacked"
