# Without this configuration, the workspace will be read from `rust-runtime`, causing the build to fail.
[workspace]
resolver = "2"
members = [
    "pokemon-service-common",
    "pokemon-service",
    "pokemon-service-tls",
    "pokemon-service-lambda",
    "pokemon-service-server-sdk",
    "pokemon-service-client",
<<<<<<< HEAD
=======
    "pokemon-service-client-usage",

>>>>>>> release-2023-11-01
]

[profile.release]
lto = true
