#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
compute_environment_name = "smithy_rs_benchmark"
type = "Managed"
state = "Enabled"

#service_role = null 

[compute_resource]
    type = "Ec2"
    allocation_strategy = "BEST_FIT"
    minv_cpus = 0
    maxv_cpus = 256
    instance_types = ["c7g.2xlarge"]
    instance_role = "SmithyRs_CompileTimeBenchmarking_Ec2Role"

[compute_resource.launch_template]
    launch_template_name = "smithy_rs_benchmarking"
    version = "1"
