[package]
name = "aws-types"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "Top-level types for the AWS SDK."
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[dependencies]
tracing = "0.1"
smithy-async = { path = "../../../rust-runtime/smithy-async" }
zeroize = "1.4.1"

[dev-dependencies]
futures-util = "0.3.16"

[build-dependencies]
rustc_version = "0.4.0"
