[package]
name = "aws-auth"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
license = "Apache-2.0"
edition = "2018"

[features]
default = []
tokio-credentials = ["tokio"]

[dependencies]
smithy-http = { path = "../../../rust-runtime/smithy-http" }
tokio = { version = "1", features = ["rt", "sync", "time", "macros"], optional = true }
tracing = "0.1.25"
zeroize = "1.2.0"

[dev-dependencies]
env_logger = "*"
test-env-log = { version = "0.2.7", features = ["trace"] }
tokio = { version = "1", features = ["macros", "test-util"] }
tracing-subscriber = { version = "0.2.16", features = ["fmt"] }
