[package]
name = "pokemon-service"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
hyper = {version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.2", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "std", "env-filter"] }

aws-smithy-http-server = { path = "../../" }
pokemon-service-sdk = { path = "../pokemon-service-sdk/" }

[build-dependencies]
fs_extra = "1"

[dev-dependencies]
assert_cmd = "2.0"
aws-smithy-client  = { path = "../../../aws-smithy-client/", features = ["rustls"] }
criterion = { version = "0.3", features = ["async_tokio", "html_reports"] }
eyre = "0.6"
pokemon-service-client = { path = "../pokemon-service-client/" }
pretty_assertions = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
