[package]
name = "pokemon-service"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
hyper = {version = "0.14", features = ["server"] }
tokio = "1"
tower = "0.4"
tower-http = { version = "0.2", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Local paths
aws-smithy-http-server = { path = "../../" }
pokemon-service-sdk = { path = "../pokemon-service-sdk/" }

[dev-dependencies]
assert_cmd = "2.0"

# Local paths
aws-smithy-client  = { path = "../../../aws-smithy-client/", features = ["rustls"] }
pokemon-service-client = { path = "../pokemon-service-client/" }
