allowed_external_types = [
    "aws_smithy_runtime_api::*",
    "aws_smithy_async::*",

    # Used for creating hyper connectors in the hyper feature and test-util features
    "tower_service::Service",

    # TODO(https://github.com/smithy-lang/smithy-rs/issues/1193): Once tooling permits it, only allow the following types in the `hyper-014` feature
    "hyper::client::client::Builder",
    "hyper::client::connect::Connection",
    "tokio::io::async_read::AsyncRead",
    "tokio::io::async_write::AsyncWrite",
    "http::uri::Uri",
]
