[package]
name = "snowball-code-examples"
version = "0.1.0"
authors = ["Landon James <lnj@amazon.com>", "Doug Schwartz <dougsch@amazon.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { path = "../../build/aws-sdk/sdk/aws-config" }
aws-sdk-snowball = { path = "../../build/aws-sdk/sdk/snowball" }
aws-types = { path = "../../build/aws-sdk/sdk/aws-types" }
tokio = { version = "1", features = ["full"] }
structopt = { version = "0.3", default-features = false }
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
