allowed_external_types = [
    "aws_credential_types::*",
    "aws_sigv4::*",
    "aws_smithy_http::*",
    "aws_smithy_types::*",
    "aws_smithy_runtime_api::*",
    "aws_types::*",
    "http::request::Request",
    "http::response::Response",
]
