[package]
name = "template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-smithy-types = {path = "./"}

[features]
serde-serialize = ["aws-smithy-types/serde-serialize"]
serde-deserialize = ["aws-smithy-types/serde-deserialize"]
