[package]
name = "aws-sigv4"
version = "0.1.0"
authors = ["David Barsky <me@davidbarsky.com>", "AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
edition = "2018"
exclude = ["aws-sig-v4-test-suite/*"]
license = "MIT OR Apache-2.0"
description = "AWS SigV4 signer"

[features]
sign-http = ["http", "http-body", "percent-encoding", "serde_urlencoded"]
sign-eventstream = []
default = ["sign-http", "sign-eventstream"]

[dependencies]
bytes = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
hex = "0.4"
http = { version = "0.2", optional = true }
http-body = { version = "0.4", optional = true }
percent-encoding = { version = "2.1", optional = true }
ring = "0.16"
serde_urlencoded = { version = "0.7", optional = true }

[dev-dependencies]
pretty_assertions = "0.6"
httparse = "1"
