[package]
name = "sdk-versioner"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
edition = "2018"
license = "Apache-2.0"
publish = false

[workspace]

[dependencies]
anyhow = "1.0"
structopt = "0.3"
toml = { version = "0.5.8", features = ["preserve_order"] }
smithy-rs-tool-common = { version = "0.1", path = "../smithy-rs-tool-common" }

[dev-dependencies]
pretty_assertions = "1"
tempfile = "3"
