[package]
name = "pokemon"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[dependencies]
hyper = {version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.2", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "std", "env-filter"] }

aws-smithy-http-server = { path = "../../" }
pokemon-sdk = { path = "./pokemon-sdk/" }

[build-dependencies]
fs_extra = "1"

# Without this empty workspace configuration, the workspace would be read from `rust-runtime`,
# causing the build to fail.
[workspace]
members = [
    ".",
    "pokemon-sdk",
    "pokemon-client"
]
