[package]
name = "lambda"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Zelda Hessler <zhessler@amazon.com>"]
edition = "2018"

[dependencies]
async-stream = "0.3"
aws-http = { path = "../../build/aws-sdk/aws-http"}
aws-hyper = { path = "../../build/aws-sdk/aws-hyper"}
aws-config = { path = "../../build/aws-sdk/aws-config"}
aws-sdk-lambda = { path = "../../build/aws-sdk/lambda" }
base64 = "0.13"
bytes = "1"
futures-core = "0.3"
http = "0.2.3"
serde_json = "1"
smithy-client = { path = "../../build/aws-sdk/smithy-client", features = ["test-util"] }
smithy-eventstream = { path = "../../build/aws-sdk/smithy-eventstream" }
smithy-http = { path = "../../build/aws-sdk/smithy-http" }
tokio  = { version = "1", features = ["full"]}
tracing-subscriber = "0.2.18"
