[package]
name = "pokemon_service"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
hyper = {version = "0.14", features = ["server"] }
lambda_http = { git = "https://github.com/awslabs/aws-lambda-rust-runtime", rev ="3e378187896da8b493f6e46e6a9c232e0419a5f3" }
tokio = "1"
tower = "0.4"
tower-http = { version = "0.2", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Local paths
aws-smithy-http-server = { path = "../../" }
pokemon_service_sdk = { path = "../pokemon_service_sdk/" }

[dev-dependencies]
assert_cmd = "2.0"
home = "0.5"
wrk-api-bench = "0.0.7"

# Local paths
aws-smithy-client  = { path = "../../../aws-smithy-client/", features = ["rustls"] }
pokemon_service_client = { path = "../pokemon_service_client/" }

[[bin]]
name = "bootstrap"
path = "src/main.rs"

[package.metadata.lambda.env]
RUST_LOG = "smithy_http_tower::dispatch=trace,smithy_http::middleware=trace,aws_smithy_http_server=trace"
