[package]
name = "kinesis-put-record"
version = "0.1.0"
authors = ["Doug Schwartz <dougsch@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kinesis = { path = "../../build/aws-sdk/kinesis" }
aws-hyper = { path = "../../build/aws-sdk/aws-hyper"}
tokio = { version = "1", features = ["full"] }
base64 = "0.13.0"
structopt = { version = "0.3", default-features = false }
tracing-subscriber = { version = "0.2.16", features = ["fmt"] }
