[package]
name = "pokemon-service"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Smithy-rs Server Team <smithy-rs-server@amazon.com>"]
description = "A smithy Rust service to retrieve information about Pokémon."

[dependencies]
# TODO(https://github.com/smithy-lang/smithy-rs/issues/3398): Unpin the clap dependency once the SDK MSRV is Rust 1.74.
# Clap was added and pinned to 4.4.x because 4.5.x requires an MSRV of Rust 1.74.
# Since the SDK MSRV is 1.72, this causes it to fail to compile.
clap = { version = "~4.4", features = ["derive"] }
http = "0.2"
hyper = { version = "0.14.26", features = ["server"] }
tokio = "1.26.0"
tower = "0.4"
tracing = "0.1"

# Local paths
aws-smithy-http-server = { path = "../../rust-runtime/aws-smithy-http-server", features = ["request-id"] }
pokemon-service-server-sdk = { path = "../pokemon-service-server-sdk/" }
pokemon-service-common = { path = "../pokemon-service-common/" }

[dev-dependencies]
assert_cmd = "2.0"
async-stream = "0.3"
rand = "0.8.5"
serial_test = "1.0.0"

# We use hyper client in tests
hyper = { version = "0.14.26", features = ["server", "client"] }

# This dependency is only required for testing the `pokemon-service-tls` program.
hyper-rustls = { version = "0.24", features = ["http2"] }

# Local paths
aws-smithy-http = { path = "../../rust-runtime/aws-smithy-http/" }
pokemon-service-client = { path = "../pokemon-service-client/" }
