[package]
name = "aws-smithy-token-bucket"
version = "0.0.0-smithy-rs-head"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Zelda Hessler <zhessler@amazon.com>"]
description = "A token bucket trait and implementors of that trait used to control request send rates."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.25", features = ["sync"] }
aws-smithy-types = { path = "../aws-smithy-types" }
http = "0.2.8"
http-body = "0.4.5"
