on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
    - tools/**
  # TODO: Remove once verified working since it should not run on pull request
  pull_request:

env:
  ecr_repository: public.ecr.aws/w0m4q9l7/github-awslabs-smithy-rs-ci

jobs:
  rebuild-docker-build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image
      run: |
        cd tools/ci-build
        docker build -t ${{ env.ecr_repository }}:latest --file build-image.dockerfile .
    - name: Acquire credentials
      with:
        role-to-assume: ${{ secrets.SMITHY_RS_PUBLIC_ECR_PUSH_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: us-west-2
    - name: Upload image
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
        docker push ${{ env.ecr_repository }}:latest
