on: [push]

name: CI

jobs:
  unit-tests:
    name: smithy-rs unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: test
        run: ./gradlew :codegen:test
