on: [push]

name: CI

jobs:
  style:
    name: smithy-rs style checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: ktlint
        run: ./gradlew ktlint
  unit-tests:
    name: Codegen unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: test
        run: ./gradlew :codegen:test
      # TODO: when the multi repo integration tests are merged, update this to glob all of them
      - uses: actions/upload-artifact@v2
        name: Upload Codegen Output for inspection
        with:
          name: codegen-output
          path: codegen-test/build/smithyprojections/codegen-test/source/rust-codegen/
  integration-tests:
    name: Codegen integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Gradle Cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v2
        name: Cargo Cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: set REPO_ROOT
        run: echo "REPO_ROOT=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: integration-tests
        run: ./gradlew :codegen-test:test
  runtime-tests:
    name: Rust runtime tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: runtime tests
        working-directory: rust-runtime
        run: ./test.sh
