name: codegen diff preview
# This job will generate a codegen diff, upload it to S3, and link to it in a comment on the PR.
on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
env:
  java_version: 11
jobs:
  generate-diff:
    runs-on: ubuntu-latest
    name: Generate diff and upload to S3
    env:
      AWS_REGION: us-west-2
      DIFF_FILE_NAME: diff-${{ github.event.pull_request.base.sha }}-${{ github.sha }}.html
      S3_BUCKET_NAME: ${{ secrets.CODEGEN_DIFF_ACTION_S3_BUCKET_NAME }}
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      name: Gradle Cache
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    # JDK is needed to generate code
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}
    # Node is needed to run diff2html
    - name: Set up NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install diff2html-cli
      run: npm install -g diff2html-cli@5.1.11
    # This generates the diff HTML named ${DIFF_FILE_NAME}
    - name: Generate diff
      run: |
        echo "Diff will be generated into ${DIFF_FILE_NAME}"
        ./tools/codegen-diff-revisions.sh . ${{ github.event.pull_request.base.sha }}
    - uses: aws-actions/configure-aws-credentials@v1
      name: Acquire credentials for uploading to S3
      with:
        role-to-assume: ${{ secrets.CODEGEN_DIFF_ACTION_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: us-west-2
    - name: Upload diff to S3
      run: aws s3 cp "${DIFF_FILE_NAME}" "s3://${S3_BUCKET_NAME}/${DIFF_FILE_NAME}"
    - uses: actions/github-script@v5
      # NOTE: if comments on each commit become bothersome, add a check that github.event.pull_request.action == "opened"
      if: ${{ github.head_ref != null }}
      with:
        script: |
          const { DIFF_FILE_NAME } = process.env;

          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `A new generated diff is ready to view: https://dfzuyhsjp8czs.cloudfront.net/${DIFF_FILE_NAME}`
          })
