name: Server SDK tests and benchmarks
# This job will run the server SDK integration tests amd benchmarks using the Pokémon service model.
on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
env:
  java_version: 11
  rust_version: 1.56.1
  rust_toolchain_components: clippy,rustfmt
  apt_dependencies: libssl-dev git gnuplot jq

jobs:
  run-e2e-integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      name: Gradle Cache
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.rust_version }}
        components: ${{ env.rust_toolchain_components }}
        default: true
    - name: Run integration tests
      run: |
        cd rust-runtime/aws-smithy-http-server/examples && \
          make && cargo test

  run-benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      name: Gradle Cache
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/cache@v2
      name: Benchmarks Cache
      with:
        path: ~/.wrk-api-bench
        key: ${{ runner.os }}-wrk-api-bench
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.rust_version }}
        components: ${{ env.rust_toolchain_components }}
        default: true
    - name: Install benchmarks dependencies
      run: sudo apt-get update && sudo apt-get install -y ${{ env.apt_dependencies }}
    # Ubuntu 20.04 doesn't have wrk packaged, hence we need to build it 🤦
    - name: Install wrk
      run: |
        git clone https://github.com/wg/wrk.git /tmp/wrk-build && \
          cd /tmp/wrk-build && make -j8 wrk && sudo cp wrk /usr/local/bin
    - name: Run benchmark
      run: |
        cd rust-runtime/aws-smithy-http-server/examples && \
          make && cargo test --release --features benchmarks && \
          for x in ~/.wrk-api-bench/*; do
            echo $x
            cat $x |jq .
          done
