[package]
name = "dynamo-put-item"
version = "0.1.0"
authors = ["Doug Schwartz <dougsch@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynamodb = { path = "../../build/aws-sdk/dynamodb" }
aws-hyper = { path = "../../build/aws-sdk/aws-hyper"}
tokio = { version = "1", features = ["full"] }
structopt = { version = "0.3", default-features = false }

# used only to enable basic logging:
# env_logger = "0.8.2"
tracing-subscriber = { version = "0.2.16", features = ["fmt"] }
